# This buildspec assumes you are using jasondour/codebuild-hugo as your image.
#
# Any Hugo extended version image will do, but path to Hugo may change.
#
# Also, this spec uses two Environment Variables:
#     BASE_URL - The base URL of the site being built.
#     TARGET - The deployment target from your config.yaml.

version: 0.2

phases:
  install:
    commands:
      - echo "No install phase actions."
  pre_build:
    commands:
      - echo "No pre-build phase actions."
  build:
    commands:
      - echo "Starting build phase..."
      - cd ${CODEBUILD_SRC_DIR}/src
      - /hugo --baseURL ${BASE_URL}
  post_build:
    commands:
      - echo "Starting post-build phase..."
      - cd ${CODEBUILD_SRC_DIR}/src
      - /hugo deploy --target ${TARGET} --maxDeletes -1
      - cd ${CODEBUILD_SRC_DIR}
      - for i in `find out -mindepth 2 -name index.html | sed "s#^out/##" | xargs -I{} -n1 dirname {}`; do echo "COPYOBJ ${i}/index.html -> ${i}/"; aws s3api copy-object --copy-source ${TARGET}/${i}/index.html --bucket ${TARGET} --key ${i}/ --content-type text/html; done
artifacts:
  files:
    - "README.md"
  discard-paths: no
  base-directory: ""
