# Don't define baseURL here.  Define is as part of test/build pipeline.
# baseURL: https://some.domain/

languageCode: en-us

title: Some Domain
theme: robotico

# Directory Structure For Hugo
#
# First, let's set the output directory...
publishDir: out
# ...then put Hugo theme and templating into a hugo hierarchy...
archetypeDir: hugo/archetypes
assetDir: hugo/assets
layoutDir: hugo/layouts
themesDir: hugo/themes
resourceDir: hugo/resources
# ...and finally author-managed data in a src hierarchy.
contentDir: src/content
dataDir: src/data
staticDir: src/static

deployment:
    targets:
        -   name: some-domain-web
            URL: s3://some-domain-web?region=us-east-2
            cloudFrontDistributionID: A1BCD123EFGH4
        -   name: web-oddity-dev
            URL: s3://some-domain-web-dev?region=us-east-2
            cloudFrontDistributionID: A1BCD123EFGH4
